epochs = 150
number_of_clauses = 500
t = 400
s = 1.0220875518939276
depth = 7
hypervector_size = 512
hypervector_bits = 4
message_size = 512
message_bits = 2
double_hashing = true
max_included_literals = 32
