epochs = 100
number_of_clauses = 100
t = 800
s = 2.599178316287909
depth = 3
hypervector_size = 1024
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = true
max_included_literals = 32
