epochs = 50
number_of_clauses = 200
t = 200
s = 1.8203649789157568
depth = 3
hypervector_size = 1024
hypervector_bits = 4
message_size = 256
message_bits = 2
double_hashing = false
max_included_literals = 32
