epochs = 50
number_of_clauses = 200
t = 400
s = 2.5732051944597134
depth = 5
hypervector_size = 1024
hypervector_bits = 4
message_size = 256
message_bits = 4
double_hashing = false
max_included_literals = 32
