epochs = 100
number_of_clauses = 100
t = 800
s = 1.231369657708578
depth = 7
hypervector_size = 512
hypervector_bits = 4
message_size = 1024
message_bits = 1
double_hashing = true
max_included_literals = 32
