epochs = 150
number_of_clauses = 500
t = 200
s = 2.9923758003736234
depth = 5
hypervector_size = 256
hypervector_bits = 1
message_size = 256
message_bits = 2
double_hashing = true
max_included_literals = 8
