epochs = 100
number_of_clauses = 500
t = 200
s = 1.0039963735961916
depth = 7
hypervector_size = 1024
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = true
max_included_literals = 32
