epochs = 100
number_of_clauses = 100
t = 100
s = 2.4734594606022755
depth = 7
hypervector_size = 256
hypervector_bits = 1
message_size = 1024
message_bits = 1
double_hashing = false
max_included_literals = 32
