epochs = 50
number_of_clauses = 100
t = 800
s = 2.425804973182354
depth = 7
hypervector_size = 256
hypervector_bits = 4
message_size = 256
message_bits = 2
double_hashing = false
max_included_literals = 8
