epochs = 150
number_of_clauses = 100
t = 100
s = 2.042419725088182
depth = 7
hypervector_size = 256
hypervector_bits = 1
message_size = 512
message_bits = 4
double_hashing = true
max_included_literals = 32
