epochs = 150
number_of_clauses = 500
t = 200
s = 2.7001431109237517
depth = 3
hypervector_size = 256
hypervector_bits = 2
message_size = 256
message_bits = 2
double_hashing = false
max_included_literals = 16
