epochs = 100
number_of_clauses = 100
t = 200
s = 2.550184248577733
depth = 3
hypervector_size = 256
hypervector_bits = 1
message_size = 1024
message_bits = 4
double_hashing = false
max_included_literals = 32
