epochs = 150
number_of_clauses = 100
t = 400
s = 2.7044158178230795
depth = 5
hypervector_size = 1024
hypervector_bits = 2
message_size = 512
message_bits = 2
double_hashing = true
max_included_literals = 16
