epochs = 50
number_of_clauses = 100
t = 800
s = 2.2962705775809056
depth = 5
hypervector_size = 256
hypervector_bits = 1
message_size = 512
message_bits = 2
double_hashing = false
max_included_literals = 16
