epochs = 50
number_of_clauses = 500
t = 200
s = 1.735285776872477
depth = 3
hypervector_size = 512
hypervector_bits = 2
message_size = 1024
message_bits = 2
double_hashing = true
max_included_literals = 8
