epochs = 150
number_of_clauses = 100
t = 400
s = 2.7944207819622244
depth = 5
hypervector_size = 256
hypervector_bits = 4
message_size = 512
message_bits = 1
double_hashing = true
max_included_literals = 16
