epochs = 150
number_of_clauses = 500
t = 200
s = 2.4830357791581052
depth = 5
hypervector_size = 512
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = true
max_included_literals = 8
