epochs = 150
number_of_clauses = 100
t = 100
s = 1.952712547841514
depth = 5
hypervector_size = 256
hypervector_bits = 1
message_size = 256
message_bits = 4
double_hashing = true
max_included_literals = 16
