epochs = 50
number_of_clauses = 100
t = 200
s = 0.9347146531831523
depth = 5
hypervector_size = 256
hypervector_bits = 2
message_size = 1024
message_bits = 4
double_hashing = true
max_included_literals = 8
