epochs = 50
number_of_clauses = 100
t = 200
s = 1.9053571806637548
depth = 5
hypervector_size = 256
hypervector_bits = 4
message_size = 512
message_bits = 4
double_hashing = false
max_included_literals = 16
