epochs = 150
number_of_clauses = 200
t = 100
s = 0.9521839600259211
depth = 7
hypervector_size = 256
hypervector_bits = 1
message_size = 256
message_bits = 4
double_hashing = true
max_included_literals = 8
