epochs = 100
number_of_clauses = 100
t = 200
s = 1.2133644854479124
depth = 5
hypervector_size = 1024
hypervector_bits = 4
message_size = 256
message_bits = 4
double_hashing = false
max_included_literals = 16
