epochs = 100
number_of_clauses = 100
t = 800
s = 2.5039838373137453
depth = 3
hypervector_size = 256
hypervector_bits = 2
message_size = 1024
message_bits = 4
double_hashing = false
max_included_literals = 8
