epochs = 50
number_of_clauses = 500
t = 800
s = 1.5480305232109401
depth = 5
hypervector_size = 1024
hypervector_bits = 1
message_size = 512
message_bits = 2
double_hashing = false
max_included_literals = 16
