epochs = 150
number_of_clauses = 200
t = 800
s = 2.1187843040621788
depth = 3
hypervector_size = 256
hypervector_bits = 2
message_size = 1024
message_bits = 2
double_hashing = false
max_included_literals = 8
