epochs = 50
number_of_clauses = 200
t = 100
s = 1.3189096623664778
depth = 7
hypervector_size = 256
hypervector_bits = 4
message_size = 512
message_bits = 1
double_hashing = false
max_included_literals = 16
