epochs = 150
number_of_clauses = 500
t = 100
s = 1.6720364832282042
depth = 3
hypervector_size = 512
hypervector_bits = 4
message_size = 1024
message_bits = 4
double_hashing = true
max_included_literals = 16
