epochs = 150
number_of_clauses = 100
t = 400
s = 1.5020365082308658
depth = 7
hypervector_size = 512
hypervector_bits = 4
message_size = 512
message_bits = 4
double_hashing = true
max_included_literals = 16
