epochs = 50
number_of_clauses = 200
t = 800
s = 1.806553415213793
depth = 5
hypervector_size = 512
hypervector_bits = 2
message_size = 512
message_bits = 2
double_hashing = true
max_included_literals = 8
