epochs = 150
number_of_clauses = 200
t = 200
s = 2.6771353517203877
depth = 3
hypervector_size = 1024
hypervector_bits = 2
message_size = 1024
message_bits = 1
double_hashing = false
max_included_literals = 8
