epochs = 50
number_of_clauses = 500
t = 400
s = 1.8489696763551806
depth = 7
hypervector_size = 1024
hypervector_bits = 4
message_size = 1024
message_bits = 2
double_hashing = false
max_included_literals = 16
