epochs = 50
number_of_clauses = 100
t = 200
s = 2.5648286494882884
depth = 3
hypervector_size = 1024
hypervector_bits = 4
message_size = 256
message_bits = 4
double_hashing = true
max_included_literals = 8
