epochs = 100
number_of_clauses = 200
t = 800
s = 2.8167415460488137
depth = 3
hypervector_size = 256
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = false
max_included_literals = 16
