epochs = 100
number_of_clauses = 200
t = 400
s = 1.0925592802025532
depth = 7
hypervector_size = 512
hypervector_bits = 1
message_size = 512
message_bits = 4
double_hashing = false
max_included_literals = 8
