epochs = 50
number_of_clauses = 500
t = 100
s = 2.844047812900758
depth = 7
hypervector_size = 1024
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = false
max_included_literals = 8
