epochs = 50
number_of_clauses = 200
t = 200
s = 2.430047128240151
depth = 5
hypervector_size = 512
hypervector_bits = 2
message_size = 1024
message_bits = 1
double_hashing = false
max_included_literals = 8
