epochs = 100
number_of_clauses = 200
t = 200
s = 2.0657626586171096
depth = 3
hypervector_size = 512
hypervector_bits = 2
message_size = 512
message_bits = 2
double_hashing = false
max_included_literals = 8
