epochs = 100
number_of_clauses = 200
t = 800
s = 1.2196903750997097
depth = 5
hypervector_size = 512
hypervector_bits = 1
message_size = 512
message_bits = 2
double_hashing = false
max_included_literals = 16
