epochs = 100
number_of_clauses = 500
t = 800
s = 2.901679546221615
depth = 5
hypervector_size = 256
hypervector_bits = 1
message_size = 256
message_bits = 1
double_hashing = true
max_included_literals = 16
