epochs = 150
number_of_clauses = 100
t = 200
s = 2.9278344161336936
depth = 7
hypervector_size = 1024
hypervector_bits = 2
message_size = 256
message_bits = 4
double_hashing = true
max_included_literals = 16
