epochs = 100
number_of_clauses = 100
t = 200
s = 1.1123839247342104
depth = 5
hypervector_size = 1024
hypervector_bits = 2
message_size = 1024
message_bits = 1
double_hashing = false
max_included_literals = 32
