epochs = 100
number_of_clauses = 100
t = 200
s = 1.856078489544451
depth = 5
hypervector_size = 1024
hypervector_bits = 4
message_size = 256
message_bits = 1
double_hashing = true
max_included_literals = 32
