epochs = 50
number_of_clauses = 200
t = 800
s = 0.9432331931804726
depth = 5
hypervector_size = 512
hypervector_bits = 4
message_size = 256
message_bits = 2
double_hashing = false
max_included_literals = 8
