epochs = 100
number_of_clauses = 200
t = 800
s = 2.5127978426019713
depth = 3
hypervector_size = 256
hypervector_bits = 2
message_size = 1024
message_bits = 1
double_hashing = false
max_included_literals = 8
