epochs = 50
number_of_clauses = 200
t = 400
s = 2.9784633073430076
depth = 5
hypervector_size = 256
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = false
max_included_literals = 32
