epochs = 50
number_of_clauses = 500
t = 800
s = 2.653089126778159
depth = 7
hypervector_size = 1024
hypervector_bits = 4
message_size = 256
message_bits = 1
double_hashing = false
max_included_literals = 8
