epochs = 50
number_of_clauses = 200
t = 100
s = 1.1347668552191503
depth = 5
hypervector_size = 512
hypervector_bits = 1
message_size = 256
message_bits = 4
double_hashing = true
max_included_literals = 32
