epochs = 50
number_of_clauses = 500
t = 800
s = 2.256810175167637
depth = 3
hypervector_size = 512
hypervector_bits = 1
message_size = 1024
message_bits = 2
double_hashing = true
max_included_literals = 16
