epochs = 50
number_of_clauses = 500
t = 400
s = 0.8772304508092569
depth = 7
hypervector_size = 1024
hypervector_bits = 2
message_size = 256
message_bits = 2
double_hashing = true
max_included_literals = 32
