epochs = 50
number_of_clauses = 200
t = 400
s = 1.553157580541745
depth = 5
hypervector_size = 512
hypervector_bits = 4
message_size = 1024
message_bits = 4
double_hashing = true
max_included_literals = 16
