epochs = 50
number_of_clauses = 100
t = 100
s = 2.152776120560334
depth = 5
hypervector_size = 256
hypervector_bits = 4
message_size = 1024
message_bits = 2
double_hashing = false
max_included_literals = 8
