epochs = 50
number_of_clauses = 500
t = 400
s = 1.1984083108133685
depth = 5
hypervector_size = 1024
hypervector_bits = 2
message_size = 256
message_bits = 4
double_hashing = false
max_included_literals = 8
