epochs = 150
number_of_clauses = 500
t = 100
s = 1.897884598323201
depth = 5
hypervector_size = 256
hypervector_bits = 1
message_size = 512
message_bits = 4
double_hashing = false
max_included_literals = 32
