epochs = 150
number_of_clauses = 500
t = 100
s = 2.171713648518594
depth = 7
hypervector_size = 512
hypervector_bits = 1
message_size = 1024
message_bits = 2
double_hashing = false
max_included_literals = 16
