epochs = 150
number_of_clauses = 100
t = 800
s = 1.305719016131911
depth = 7
hypervector_size = 1024
hypervector_bits = 4
message_size = 512
message_bits = 4
double_hashing = false
max_included_literals = 32
