epochs = 150
number_of_clauses = 200
t = 200
s = 2.1674958719738484
depth = 3
hypervector_size = 512
hypervector_bits = 4
message_size = 256
message_bits = 1
double_hashing = true
max_included_literals = 32
