epochs = 50
number_of_clauses = 100
t = 800
s = 2.823368080153835
depth = 5
hypervector_size = 256
hypervector_bits = 4
message_size = 512
message_bits = 2
double_hashing = true
max_included_literals = 8
