epochs = 150
number_of_clauses = 200
t = 800
s = 1.0232100506710238
depth = 3
hypervector_size = 512
hypervector_bits = 4
message_size = 512
message_bits = 2
double_hashing = false
max_included_literals = 16
