epochs = 100
number_of_clauses = 200
t = 800
s = 2.517971333275211
depth = 5
hypervector_size = 1024
hypervector_bits = 2
message_size = 1024
message_bits = 2
double_hashing = true
max_included_literals = 16
