epochs = 50
number_of_clauses = 100
t = 200
s = 1.0154001612328452
depth = 7
hypervector_size = 1024
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = false
max_included_literals = 8
