epochs = 50
number_of_clauses = 500
t = 400
s = 1.2112430364367046
depth = 3
hypervector_size = 256
hypervector_bits = 4
message_size = 1024
message_bits = 4
double_hashing = true
max_included_literals = 16
