epochs = 100
number_of_clauses = 200
t = 400
s = 2.20620028793355
depth = 7
hypervector_size = 512
hypervector_bits = 2
message_size = 1024
message_bits = 2
double_hashing = true
max_included_literals = 16
