epochs = 100
number_of_clauses = 200
t = 100
s = 2.596739782344569
depth = 7
hypervector_size = 256
hypervector_bits = 1
message_size = 512
message_bits = 2
double_hashing = true
max_included_literals = 8
