epochs = 150
number_of_clauses = 100
t = 400
s = 1.758119256623036
depth = 3
hypervector_size = 1024
hypervector_bits = 2
message_size = 512
message_bits = 4
double_hashing = true
max_included_literals = 8
