epochs = 150
number_of_clauses = 200
t = 200
s = 1.2922024372617928
depth = 3
hypervector_size = 256
hypervector_bits = 4
message_size = 512
message_bits = 4
double_hashing = true
max_included_literals = 16
