epochs = 100
number_of_clauses = 500
t = 800
s = 2.3182518905283462
depth = 3
hypervector_size = 256
hypervector_bits = 1
message_size = 256
message_bits = 2
double_hashing = false
max_included_literals = 16
