epochs = 50
number_of_clauses = 500
t = 800
s = 2.214491807500077
depth = 5
hypervector_size = 1024
hypervector_bits = 1
message_size = 512
message_bits = 1
double_hashing = true
max_included_literals = 16
